# fly.toml app configuration file generated for oracle on 2024-12-19T10:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "oracle-hyperbridge"
primary_region = "iad"

[build]

[env]
  PORT = "5001"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/submissions"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512 