[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.23"

# Allow Foundry to write files inside the 'out' directory (for vm.writeFile)
fs_permissions = [
  { access = "read", path = "./" },
  { access = "write", path = "./out" }
]

# Define RPC endpoints as aliases you can reference with --rpc-url or --fork-url
[rpc_endpoints]
testnet = "${TESTNET_RPC_URL}"